name: "running unit test, build docker image"
on:
  push:
    branches:
       - "main"
jobs:
  unit-test:
    name: "unit test"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: setup go
        uses: actions/setup-go@v2
        with: 
          go-version: 1.17.3
      - name: running unit test
        run: go test ./... -cover

  build-push-docker:
    name: "build docker image then push to docker hub"
    runs-on: "ubuntu-latest"
    needs: unit-test
    steps:
      - uses: actions/checkout@v2
      - name: build docker
        run: docker build -t fakhriinaufal/presence-app-backend:1.0.0
      - name: login docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: push image to docker hub registry
        run: docker push fakhriinaufal/presence-app-backend:latest
  deployment:
    name: "deploy to ec2"
    runs-on: "ubuntu-latest"
    needs: build-push-docker
    steps:
      - uses: actions/checkout@v2
      - name: configure ssh
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_KEY: ${{ secrets.PRESENCE_APP_BACKEND_PEM }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/presence_app_backend.pem
          chmod 700 ~/.ssh/presence_app_backend.pem
          cat >> ~/.ssh/config << END
          Host development
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/alterra_academy_aws.pem
            StrictHostKeyChecking=no
          END
      - name: "connect ec2, remove container, pull from registry, start container"
        run: ssh development 'docker rm -f $(docker ps -a -q)' || true && docker pull fakhriinaufal/presence-app-backend:latest && docker run -p 8000:8000 --name presence-app-backend fakhriinaufal/presence-app-backend:latest
